<#
.SYNOPSIS
    Simulates Configuration Migration data export in mock_deploy mode.

.DESCRIPTION
    Parses the schema XML to list entities that would be exported, then creates
    a placeholder config-data.zip so that downstream artifact upload steps find
    the expected file. No Dataverse connection is made.

.PARAMETER SchemaFile
    Relative path to the Configuration Migration schema XML file.

.PARAMETER OutputZipPath
    Path for the placeholder output ZIP (e.g. out/MySolution/config/config-data.zip).

.PARAMETER SourceEnvironmentUrl
    Source environment URL (logged for information only, no connection made).

.PARAMETER RunNumber
    GitHub run number (included in placeholder content).
#>
param(
    [Parameter(Mandatory)][string] $SchemaFile,
    [Parameter(Mandatory)][string] $OutputZipPath,
    [string] $SourceEnvironmentUrl = '(none provided)',
    [string] $RunNumber            = ''
)

$ErrorActionPreference = 'Stop'

@"
## 🧪 Export Configuration Data — Simulation
_mock_deploy=true — parsing schema locally, no Dataverse connection used_

**Schema file:** ``$SchemaFile``
**Source env:**  ``$SourceEnvironmentUrl``
**Output:**      ``$OutputZipPath``

"@ | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding utf8 -Append

if (-not (Test-Path $SchemaFile)) {
    Write-Host "::warning::Schema file not found at '$SchemaFile' — skipping config-data simulation."
    "⚠️ Schema file not found — no config-data.zip produced." |
        Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding utf8 -Append
    exit 0
}

# Parse entity names from schema XML
[xml]$schema = Get-Content $SchemaFile -Encoding UTF8
$entities = $schema.SelectNodes('//*[local-name()="entity"]')

@"
| Entity / Table | Simulated Status |
| --- | --- |
"@ | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding utf8 -Append

if ($entities.Count -gt 0) {
    foreach ($ent in $entities) {
        $name = $ent.GetAttribute('name')
        if (-not $name) { $name = $ent.GetAttribute('displayname') }
        if (-not $name) { $name = 'unknown' }
        "| ``$name`` | 🧪 Would export records |" |
            Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding utf8 -Append
    }
} else {
    "| (no entities found in schema) | — |" |
        Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding utf8 -Append
}

# Create placeholder zip
$outDir = Split-Path $OutputZipPath -Parent
if ($outDir -and -not (Test-Path $outDir)) {
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}

$tmpFile = [System.IO.Path]::GetTempFileName()
@"
MOCK CONFIG DATA EXPORT — generated by mock_deploy simulation
Schema:  $SchemaFile
Source:  $SourceEnvironmentUrl
Run:     $RunNumber
Date:    $((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))
"@ | Set-Content -Path $tmpFile -Encoding UTF8

if (Test-Path $OutputZipPath) { Remove-Item $OutputZipPath -Force }
Compress-Archive -Path $tmpFile -DestinationPath $OutputZipPath -Force
Remove-Item $tmpFile -Force

Write-Host "✅ Placeholder config-data.zip created: $OutputZipPath"
"" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding utf8 -Append
"✅ Placeholder ``config-data.zip`` created for artifact upload." |
    Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding utf8 -Append
Write-Host "::notice::Config data export SIMULATED. Re-run without mock_deploy=true to export live data."
